
CREATE TABLE ubf59h8ecre4nbj9 (
 id INT NOT NULL AUTO_INCREMENT,
  burger_name VARCHAR (100) NOT NULL,
  devoured BOOL DEFAULT false,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);