DROP DATABASE IF EXISTS todo_db;
CREATE DATABASE IF NOT EXISTS todo_db;
USE todo_db;

CREATE TABLE todos (
 id INT AUTO_INCREMENT NOT NULL,
 description VARCHAR(255),
 createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY(id)
 );